services:
  mysql_db:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - private_network

  backend_core:
    build: .
    container_name: almoxarifado-app
    image: spring-almoxarifado:1.0
    restart: no
    ports:
      - "8082:8082"
    depends_on:
      - mysql_db
    environment:
      DATABASE_URL: jdbc:mysql://mysql_db:3306/${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_KEY: ${JWT_KEY}
    networks:
      - private_network
      - public_network

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge