server:
  port: 8080

spring:
  application:
    name: spring-almoxarifado
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3307/${DATABASE_DEV}?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL do Eureka Server

jwt:
  key: ${JWT_KEY:FrMomuJGGw3ewpb8hYZrLaUciGKPMSTDT6oYrzd6tuqSl6EHIIB7T0p1Y9WErzZLa5OPjn_0MX2MMhIwSQbxZXgBgf0BF0lbVgLbnhyqAw4Ru3iVHhTirodzYRJP9A2hIkDKxgZ6xj8UYtzGcB09tWCG4PADwatd-6ZC-wG9BIrCLVXF8cvg1Puo45FJz0OlQKpWv5c5Hu2tOMLfBFHLDIdU3FZ5iVDfH1LJ1G5oiyMIpXR9j-TNhkf_4aerrgJzc6cEHnh5seQA2N4gJia5XjGLCgwf0cLWn79upnsrqEFUUWJhQwl75WpEUKU6R0xTTEEBo0eLeXLJpXqlEqz9FMRH4qqmX_BS--Qp}
  expiration: ${JWT_EXPIRATION:900000} #15minutos

rabbitmq:
  queue:
    name: NOTIFICATION_QUEUE
  host: localhost
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  port: 8090